# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZTNjZTQ4NzliNTljMWEwZjljMWI3NjAxZDc2MmM5NGM4OGI1ZTgwYTlmZDZkYjA2YzM3ZjU4MDMzNzk2ZjljZWQzM2VhYTNmMjQ2ZjhlZmUyMzc0YzM1ZTcxMGYwYTczYmViMGZhYTRmNmNmYTllYzljYWEyMDkxYWYzNjE4YzM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
